//go:build ppc64le

package crc64

// foldKernel is the VPMSUMD fold, generated by kernel_ppc64le_gen.go into
// kernel_ppc64le.s. It requires len(p) >= 16 and len(p) % 16 == 0.
func foldKernel(p []byte, init uint64, c *foldConstants) (hi, lo uint64)

// hasKernel gates update() onto the kernel. VSX is baseline on POWER8+, so it is
// always on at runtime; it is a var (not a const) only so tests can force the
// stdlib scalar fallback for branch coverage.
var hasKernel = true
