// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·foldKernel(SB), NOSPLIT, $0-56
	MOVQ p_base+0(FP), SI
	MOVQ p_len+8(FP), CX
	MOVQ init+24(FP), DX
	MOVQ c+32(FP), R8
	MOVOU (SI), X0
	MOVQ DX, X1
	PXOR X1, X0
	ADDQ $16, SI
	SUBQ $16, CX
	MOVOU 0(R8), X2
loop:
	CMPQ CX, $16
	JB done
	MOVOA X0, X3
	PCLMULQDQ $0x00, X2, X0
	PCLMULQDQ $0x11, X2, X3
	PXOR X3, X0
	MOVOU (SI), X4
	PXOR X4, X0
	ADDQ $16, SI
	SUBQ $16, CX
	JMP loop
done:
	MOVQ X0, AX
	PEXTRQ $1, X0, BX
	MOVQ BX, hi+40(FP)
	MOVQ AX, lo+48(FP)
	RET

