// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·foldKernel(SB), NOSPLIT, $0-56
	MOVD p_base+0(FP), R0
	MOVD p_len+8(FP), R1
	MOVD init+24(FP), R2
	MOVD c+32(FP), R3
	VLD1 (R0), [V0.B16]
	VEOR V1.B16, V1.B16, V1.B16
	VMOV R2, V1.D[0]
	VEOR V1.B16, V0.B16, V0.B16
	ADD $16, R0, R0
	SUB $16, R1, R1
	VLD1 (R3), [V2.D2]
loop:
	CMP $16, R1
	BLT done
	VPMULL V0.D1, V2.D1, V3.Q1
	VPMULL2 V0.D2, V2.D2, V4.Q1
	VEOR V4.B16, V3.B16, V0.B16
	VLD1 (R0), [V5.B16]
	VEOR V5.B16, V0.B16, V0.B16
	ADD $16, R0, R0
	SUB $16, R1, R1
	B loop
done:
	VMOV V0.D[0], R4
	VMOV V0.D[1], R5
	MOVD R5, hi+40(FP)
	MOVD R4, lo+48(FP)
	RET

