//go:build ppc64le

package crc64

import "golang.org/x/sys/cpu"

// ppcMinBulk returns the smallest input the VPMSUMD kernel is engaged for, given
// whether the host is POWER9+. On POWER8 the kernel's per-call overhead (the
// MTVSRD/XXPERMDI vector-build replacing POWER9's single-op MTVSRDD, plus the
// 128->64 reduction) pushes its crossover with the scalar table path up to ~4 KiB
// (measured on cfarm112, POWER8E). Below that the scalar path is faster, so use a
// 4096 floor on pre-POWER9 hosts; POWER9+ keeps the 512 default (kernel wins from
// ~1 KiB, measured on cfarm433). Split out as a pure function so both branches are
// unit-testable on any host (the POWER9-emulated CI lane never takes the POWER8
// branch otherwise).
func ppcMinBulk(isPOWER9 bool) int {
	if !isPOWER9 {
		return 4096
	}
	return 512
}

func init() { minBulk = ppcMinBulk(cpu.PPC64.IsPOWER9) }

// foldKernel is the VPMSUMD fold, generated by kernel_ppc64le_gen.go into
// kernel_ppc64le.s. It requires len(p) >= 16 and len(p) % 16 == 0.
func foldKernel(p []byte, init uint64, c *foldConstants) (hi, lo uint64)

// hasKernel gates update() onto the kernel. The fold is now built entirely from
// ISA-2.07 ops (VPMSUMD + MTVSRD/MFVSRD/XXPERMDI), the ppc64le baseline (POWER8),
// so it runs natively on POWER8 too — measured on cfarm112 (POWER8E) to beat the
// stdlib scalar table path. (It previously used the ISA-3.0 MTVSRDD, which
// SIGILLed on POWER8 and forced a POWER9 gate; that single instruction was
// replaced by an MTVSRD + MTVSRD + XXPERMDI sequence.) It is a var (not a const)
// so tests can still force the scalar fallback for branch coverage.
var hasKernel = true
