//go:build amd64

package crc64

import "golang.org/x/sys/cpu"

// foldKernel is the PCLMULQDQ fold, generated by kernel_amd64_gen.go into
// kernel_amd64.s. It requires len(p) >= 16 and len(p) % 16 == 0.
func foldKernel(p []byte, init uint64, c *foldConstants) (hi, lo uint64)

// hasKernel gates update() onto the CLMUL kernel. It is a var (not a const) so
// tests can force it off to exercise the stdlib scalar fallback regardless of
// the host CPU. When PCLMULQDQ is absent the stdlib scalar path is used (it is
// faster than any software-emulated carryless multiply).
var hasKernel = cpu.X86.HasPCLMULQDQ
