//go:build s390x

package crc64

import "golang.org/x/sys/cpu"

// foldKernel is the VGFMAG fold, generated by kernel_s390x_gen.go into
// kernel_s390x.s. It requires len(p) >= 16 and len(p) % 16 == 0.
func foldKernel(p []byte, init uint64, c *foldConstants) (hi, lo uint64)

// hasKernel gates update() onto the vector kernel. It is a var so tests can force
// the stdlib scalar fallback. When the vector facility is absent the scalar path
// is used.
var hasKernel = cpu.S390X.HasVX
