//go:build arm64

package crc64

import "golang.org/x/sys/cpu"

// foldKernel is the PMULL fold, generated by kernel_arm64_gen.go into
// kernel_arm64.s. It requires len(p) >= 16 and len(p) % 16 == 0.
func foldKernel(p []byte, init uint64, c *foldConstants) (hi, lo uint64)

// hasKernel gates update() onto the PMULL kernel. It is a var so tests can force
// it off to exercise the stdlib scalar fallback. When PMULL is absent (or not
// reported, e.g. on darwin where the cpu package does not probe it) the stdlib
// scalar path is used.
var hasKernel = cpu.ARM64.HasPMULL
