// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·foldKernel(SB), NOSPLIT, $0-56
	MOVD p_base+0(FP), R1
	MOVD p_len+8(FP), R2
	MOVD init+24(FP), R3
	MOVD c+32(FP), R4
	MOVD (R4), R6
	MOVD 8(R4), R8
	VLVGP R8, R6, V3
	MOVDBR (R1), R9
	MOVDBR 8(R1), R10
	XOR R3, R9
	VLVGP R10, R9, V0
	ADD $16, R1
	ADD $-16, R2
loop:
	CMPBLT R2, $16, done
	MOVDBR (R1), R9
	MOVDBR 8(R1), R10
	VLVGP R10, R9, V2
	VGFMAG V3, V0, V2, V0
	ADD $16, R1
	ADD $-16, R2
	BR loop
done:
	VLGVG $0, V0, R11
	VLGVG $1, V0, R12
	MOVD R11, hi+40(FP)
	MOVD R12, lo+48(FP)
	RET

