//go:build ppc64le

package crc64

import "golang.org/x/sys/cpu"

// foldKernel is the VPMSUMD fold, generated by kernel_ppc64le_gen.go into
// kernel_ppc64le.s. It requires len(p) >= 16 and len(p) % 16 == 0.
func foldKernel(p []byte, init uint64, c *foldConstants) (hi, lo uint64)

// hasKernel gates update() onto the kernel. The generated fold uses ISA-3.0
// (POWER9) instructions (MTVSRDD) that raise SIGILL on POWER8, so it runs only
// on POWER9+; POWER8 falls back to the stdlib scalar table path. It is a var
// (not a const) so tests can also force the fallback for branch coverage.
var hasKernel = cpu.PPC64.IsPOWER9
